export const SITE_NAME = 'Ratibu Chama'
export const SITE_URL = 'https://www.ratibuchama.com'
export const SITE_TITLE = 'Ratibu Chama | Digital Chama Banking, Savings, Loans & USSD'
export const SITE_DESCRIPTION =
  'Ratibu Chama is a digital banking platform for chamas, savings groups, SACCOs, loans, USSD banking, KCB M-PESA, KPLC bills, statements, meetings, KYC, and mobile money payments in Kenya and beyond.'
export const SITE_KEYWORDS = [
  'Ratibu Chama',
  'Ratibu',
  'Ratibu Chama Kenya',
  'Ratibu Chama official website',
  'chama app Kenya',
  'digital chama banking',
  'group savings platform',
  'savings groups Kenya',
  'savings group management',
  'savings and loans platform',
  'group contribution app',
  'chama management software',
  'chama management system',
  'chama banking solution',
  'SACCO software Kenya',
  'community savings app',
  'informal savings platform',
  'ROSCA app',
  'chama savings app',
  'USSD banking Kenya',
  'USSD banking platform',
  'mobile banking for chamas',
  'mobile money contributions',
  'M-Pesa chama',
  'M-Pesa collections',
  'KCB M-PESA',
  'KPLC token payment',
  'bill payment app',
  'utility bill payments',
  'savings goals',
  'personal savings',
  'loan management',
  'loan tracking',
  'loan repayment platform',
  'meeting reminders',
  'meeting management',
  'allocation swaps',
  'transaction statements',
  'KYC verification',
  'identity verification',
  'financial inclusion',
  'community savings',
  'rotating savings group',
  'investment group platform',
  'digital finance Kenya',
  'fintech Kenya',
  'African fintech',
  'small business banking',
  'SME banking platform',
  'wallet transfers',
  'internal transfers',
  'member contributions',
  'group ledger',
  'digital ledger',
  'payment collection platform',
]
